from typing import Dict

# Все текстовые константы бота
TEXTS: Dict[str, Dict[str, str]] = {
    "RU": {
        "lang_prompt": "Выберите язык / Tilni tanlang / Choose language",
        "consent_text": (
            "<b>Согласие на обработку данных</b>\n\n🔒 Нажмите «✅ Да, согласен», если разрешаете использовать ваше имя и телефон для связи по вашему обращению. Будьте уверены — каждое заявление обязательно будет рассмотрено и останется строго конфиденциальным."
        ),
        "consent_agree": "✅ Да, согласен",
        "ask_name": "👤 Как к вам обращаться? Укажите <b>имя и фамилию</b> (например: Иван Петров).",
        "ask_phone": "📞 Напишите номер телефона. Пример: +998 90 123-45-67. Главное: должно быть не меньше 7 цифр.",
        "invalid_name": "⚠️ Имя и фамилия: от 2 до 120 символов. Пример: Иван Петров.",
        "invalid_phone": "⚠️ Не похоже на номер. Нужно хотя бы 7 цифр. Примеры: +998901234567, 90 123-45-67. Попробуйте ещё раз.",
        "choose_category": "📂 Выберите <b>категорию</b> обращения:",
        "ask_text": "📝 Опишите ситуацию. Минимум 15 символов. Пишите по делу, без личных данных третьих лиц.",
        "text_too_short": "Слишком коротко. Нужен осмысленный текст от 15 символов.",
        "attachments_hint": "📎 Пришлите вложения (фото/видео/документы/голосовые), максимум 10. Когда закончите — нажмите «Готово».",
        "btn_done": "Готово",
        "btn_skip": "Пропустить",
        "too_many_attachments": "Превышен лимит: максимум 10 вложений. Лишние не приняты.",
        "review_title": "🔍 <b>Финальная проверка</b>",
        "review_fields": "🌐 Язык: {lang}\n👤 Имя: {name}\n📞 Телефон: {phone}\n📂 Категория: {cat}\n📝 Текст: {text_sample}\n📎 Вложений: {n}",
        "btn_edit": "✏️ Изменить",
        "btn_send": "📨 Отправить",
        "edit_what": "Что хотите изменить?",
        "edit_name": "Имя",
        "edit_phone": "Телефон",
        "edit_category": "Категорию",
        "edit_text": "Текст",
        "edit_attachments": "Вложения",
        "review_back": "Вернулся к этапу: {what}. Продолжайте.",
        "submitted": "✅ Готово. Ваше обращение зарегистрировано с ID <b>{eid}</b>.\nМы свяжемся по указанному телефону.",
        "card_status_new": "новое",
        "card_status_work": "в работе",
        "card_status_closed": "закрыто",
        "admin_no_access": "Нет доступа",
        "stats_header": "<b>Статистика по последним {n} карточкам</b>",
        "stats_line": "Статусы: новое={new}, в работе={work}, закрыто={closed}\nКатегории: {cats}",
        "whereami": "chat_id: <code>{cid}</code>",
        "export_ready": "Экспорт готов. Отправляю CSV.",
        "export_empty": "Нет данных для экспорта.",
        "bitrix_error": "Внимание: Bitrix24 временно недоступен. Карточка создана, но задача не обновлена.",
        "categories": "Угрозы, Вымогательство, Шантаж, Препятствие работе, Незаконные действия, Унижение/оскорбления, Коррупция, Злоупотребление полномочиями, Другое",
        "lang_ru": "RU",
        "lang_uz": "UZ",
        "lang_en": "EN",
        "after_submit_prompt": "Создать ещё одну заявку?",
        "btn_new_request": "🆕 Создать заявку",
    },

    "UZ":{
        "lang_prompt": "Tilni tanlang / Выберите язык / Choose language",
        "consent_text": (
            "<b>Shaxsiy ma'lumotlarga rozilik</b>\n\n🔒 «✅ Roziman» ni bossangiz, murojaat bo‘yicha aloqa uchun ismingiz va telefoningizdan foydalanishga rozilik berasiz. Ishoning: har bir murojaat albatta ko‘rib chiqiladi va qat’iy maxfiy saqlanadi."
        ),
        "consent_agree": "✅ Roziman",
        "ask_name": "👤 Qanday murojaat qilamiz? <b>Ism va familiyangizni</b> kiriting (masalan: Ali Valiyev).",
        "ask_phone": "📞 Telefon raqamingizni yozing. Misol: +998 90 123‑45‑67. Eng asosiysi: kamida 7 ta raqam bo‘lsin.",
        "invalid_name": "⚠️ Ism va familiya: 2–120 belgi. Misol: Ali Valiyev.",
        "invalid_phone": "⚠️ Telefon to‘g‘ri emas. Kamida 7 ta raqam kerak. Misollar: +998901234567, 90 123‑45‑67. Qayta kiriting.",
        "choose_category": "📂 <b>Murojaat turini</b> tanlang:",
        "ask_text": "📝 Vaziyatni batafsil yozing. Kamida 15 ta belgi. Ortiqcha shaxsiy ma'lumotlarsiz.",
        "text_too_short": "Matn juda qisqa. Kamida 15 ta belgi kerak.",
        "attachments_hint": "📎 Ilovalarni yuboring (foto/video/hujjat/ovozli), maksimal 10 ta. Tugatgach «Tayyor»ni bosing.",
        "btn_done": "Tayyor",
        "btn_skip": "O‘tkazib yuborish",
        "too_many_attachments": "Limit oshib ketdi: maksimal 10 ta ilova.",
        "review_title": "🔍 <b>Yakuniy tekshiruv</b>",
        "review_fields": "🌐 Til: {lang}\n👤 Ism: {name}\n📞 Telefon: {phone}\n📂 Tur: {cat}\n📝 Matn: {text_sample}\n📎 Ilovalar: {n}",
        "btn_edit": "✏️ Tuzatish",
        "btn_send": "📨 Yuborish",
        "edit_what": "Nimani tuzatamiz?",
        "edit_name": "Ism",
        "edit_phone": "Telefon",
        "edit_category": "Tur",
        "edit_text": "Matn",
        "edit_attachments": "Ilovalar",
        "review_back": "Bosqichga qaytdik: {what}. Davom eting.",
        "submitted": "✅ Qabul qilindi. Sizning ID: <b>{eid}</b>.",
        "card_status_new": "yangi",
        "card_status_work": "jarayonda",
        "card_status_closed": "yopildi",
        "admin_no_access": "Ruxsat yo‘q",
        "stats_header": "<b>Oxirgi {n} karta bo‘yicha statistika</b>",
        "stats_line": "Holatlar: yangi={new}, jarayonda={work}, yopildi={closed}\nTurlar: {cats}",
        "whereami": "chat_id: <code>{cid}</code>",
        "export_ready": "Eksport tayyor. CSV yuborilmoqda.",
        "export_empty": "Eksport uchun ma'lumot yo‘q.",
        "bitrix_error": "Diqqat: Bitrix24 vaqtincha ishlamayapti. Karta yaratildi, lekin vazifa yangilanmadi.",
        "categories": "Tahdidlar, Talab (vymogatelstvo), Shantaj, Ishga xalaqit, Qonunga zid harakatlar, Tahqirlash, Korrupsiya, Vakolatdan suiiste'mol, Boshqa",
        "lang_ru": "RU",
        "lang_uz": "UZ",
        "lang_en": "EN",
        # Post-submit
        "after_submit_prompt": "Yana bir murojaat yuborasizmi?",
        "btn_new_request": "🆕 Yangi murojaat",
    },

    "EN": {
        "lang_prompt": "Choose language / Выберите язык / Tilni tanlang",
        "consent_text": (
            "<b>Consent</b>\n\n🔒 Tap “✅ I agree” to allow us to use your name and phone to contact you about this case. Rest assured: every submission will be reviewed and kept strictly confidential."
        ),
        "consent_agree": "✅ I agree",
        "ask_name": "👤 How should we address you? Enter your <b>first and last name</b> (e.g., John Smith).",
        "ask_phone": "📞 Type your phone number. Example: +998 90 123‑45‑67. It just needs at least 7 digits.",
        "invalid_name": "⚠️ Name and surname: 2–120 characters. Example: John Smith.",
        "invalid_phone": "⚠️ That doesn’t look like a phone number. Need at least 7 digits. Examples: +998901234567, 90 123‑45‑67. Try again.",
        "choose_category": "📂 Choose the <b>category</b>:",
        "ask_text": "📝 Describe the case. Minimum 15 characters. Keep it factual, no third‑party personal data.",
        "text_too_short": "Too short. Need at least 15 characters.",
        "attachments_hint": "📎 Send attachments (photo/video/document/voice), up to 10. Press “Done” when finished.",
        "btn_done": "Done",
        "btn_skip": "Skip",
        "too_many_attachments": "Limit exceeded: maximum 10 attachments.",
        "review_title": "🔍 <b>Final review</b>",
        "review_fields": "🌐 Language: {lang}\n👤 Name: {name}\n📞 Phone: {phone}\n📂 Category: {cat}\n📝 Text: {text_sample}\n📎 Attachments: {n}",
        "btn_edit": "✏️ Edit",
        "btn_send": "📨 Submit",
        "edit_what": "What do you want to edit?",
        "edit_name": "Name",
        "edit_phone": "Phone",
        "edit_category": "Category",
        "edit_text": "Text",
        "edit_attachments": "Attachments",
        "review_back": "Back to: {what}. Continue.",
        "submitted": "✅ Done. Your ID is <b>{eid}</b>.",
        "card_status_new": "new",
        "card_status_work": "in progress",
        "card_status_closed": "closed",
        "admin_no_access": "No access",
        "stats_header": "<b>Stats for last {n} cards</b>",
        "stats_line": "Statuses: new={new}, in progress={work}, closed={closed}\nCategories: {cats}",
        "whereami": "chat_id: <code>{cid}</code>",
        "export_ready": "Export ready. Sending CSV.",
        "export_empty": "Nothing to export.",
        "bitrix_error": "Warning: Bitrix24 is unavailable. Card created, but task update failed.",
        "categories": "Threats, Extortion, Blackmail, Work obstruction, Illegal actions, Insult/abuse, Corruption, Abuse of power, Other",
        "lang_ru": "RU",
        "lang_uz": "UZ",
        "lang_en": "EN",
        # Post-submit
        "after_submit_prompt": "Do you want to send another request?",
        "btn_new_request": "🆕 New request",
    }
}

CATEGORIES_BY_LANG = {
    "RU": [s.strip() for s in TEXTS["RU"]["categories"].split(",")],
    "UZ": [s.strip() for s in TEXTS["UZ"]["categories"].split(",")],
    "EN": [s.strip() for s in TEXTS["EN"]["categories"].split(",")],
}


def t(key: str, lang: str) -> str:
    d = TEXTS.get(lang, TEXTS["RU"])
    return d.get(key, key)
